extends SceneTree

var checks := 0
var failures := 0

func check(cond: bool, name: String) -> void:
	checks += 1
	if not cond:
		failures += 1
		printerr("FAIL: " + name)
	else:
		print("ok: " + name)

func _init():
	_test_units_and_constants()
	_test_geometry_constructors()
	_test_curve_constructors()
	_test_sketch_constructors()
	_test_part_constructors()
	_test_holes_and_fasteners()
	_test_operations()
	_test_joints_and_drafting()
	_test_io()
	print("--- DSL Parity Test Results ---")
	print("Checks: %d, Failures: %d" % [checks, failures])
	quit(1 if failures > 0 else 0)

func _test_units_and_constants() -> void:
	check(Bdg.MM == 1.0, "Bdg.MM is 1.0")
	check(Bdg.CM == 10.0, "Bdg.CM is 10.0")
	check(Bdg.M == 1000.0, "Bdg.M is 1000.0")
	check(Bdg.IN == 25.4, "Bdg.IN is 25.4")
	check(Bdg.FT == 304.8, "Bdg.FT is 304.8")
	check(Bdg.THOU == 0.0254, "Bdg.THOU is 0.0254")
	check(Bdg.Mode.ADD == BdgEnums.Mode.ADD, "Bdg.Mode enum access")
	check(Bdg.Align.CENTER == BdgEnums.Align.CENTER, "Bdg.Align enum access")

func _test_geometry_constructors() -> void:
	var p := Bdg.pos(10.0, 20.0, 30.0)
	check(p == Vector3(10, 20, 30), "Bdg.pos returns Vector3")
	var r := Bdg.rot(90.0, 0.0, 0.0)
	check(r is Quaternion, "Bdg.rot returns Quaternion")
	var loc := Bdg.location(p, r)
	check(loc is BdgLocation and loc.position == p, "Bdg.location returns BdgLocation")

func _test_curve_constructors() -> void:
	var l := Bdg.line(Vector3.ZERO, Vector3(10, 0, 0))
	check(l != null, "Bdg.line")
	var pl := Bdg.polar_line(Vector3.ZERO, 15.0, 45.0)
	check(pl != null, "Bdg.polar_line")
	var poly := Bdg.polyline([Vector3.ZERO, Vector3(5, 5, 0), Vector3(10, 0, 0)])
	check(poly != null, "Bdg.polyline")
	var fpoly := Bdg.fillet_polyline([Vector3(0, 0, 0), Vector3(20, 0, 0), Vector3(20, 20, 0)], 2.0)
	check(fpoly != null, "Bdg.fillet_polyline")
	var a3 := Bdg.arc_3pt(Vector3.ZERO, Vector3(5, 5, 0), Vector3(10, 0, 0))
	check(a3 != null, "Bdg.arc_3pt")
	var ca := Bdg.center_arc(Vector3.ZERO, 10.0, 0.0, 90.0)
	check(ca != null, "Bdg.center_arc")
	var ra := Bdg.radius_arc(Vector3.ZERO, Vector3(10, 0, 0), 10.0)
	check(ra != null, "Bdg.radius_arc")
	var sa := Bdg.sagitta_arc(Vector3.ZERO, Vector3(10, 0, 0), 2.0)
	check(sa != null, "Bdg.sagitta_arc")
	var sp := Bdg.spline([Vector3.ZERO, Vector3(5, 5, 0), Vector3(10, 2, 0), Vector3(15, 0, 0)])
	check(sp != null, "Bdg.spline")
	var bz := Bdg.bezier([Vector3.ZERO, Vector3(0, 10, 0), Vector3(10, 10, 0), Vector3(10, 0, 0)])
	check(bz != null, "Bdg.bezier")
	var hx := Bdg.helix(5.0, 20.0, 8.0)
	check(hx != null, "Bdg.helix")
	var af := Bdg.airfoil("0012", 50.0)
	check(af != null, "Bdg.airfoil")

func _test_sketch_constructors() -> void:
	var r := Bdg.rect(20.0, 10.0)
	check(r != null, "Bdg.rect")
	var rr := Bdg.rounded_rect(20.0, 10.0, 2.0)
	check(rr != null, "Bdg.rounded_rect")
	var c := Bdg.circle(10.0)
	check(c != null, "Bdg.circle")
	var el := Bdg.ellipse(15.0, 8.0)
	check(el != null, "Bdg.ellipse")
	var rp := Bdg.regular_polygon(12.0, 6)
	check(rp != null, "Bdg.regular_polygon")
	var tri := Bdg.triangle(10.0, 10.0, 10.0)
	check(tri != null, "Bdg.triangle")
	var trap := Bdg.trapezoid(20.0, 10.0, 12.0)
	check(trap != null, "Bdg.trapezoid")
	var sc2c := Bdg.slot_c2c(15.0, 4.0)
	check(sc2c != null, "Bdg.slot_c2c")
	var sov := Bdg.slot_overall(25.0, 10.0)
	check(sov != null, "Bdg.slot_overall")
	var sup := Bdg.superellipse(15.0, 10.0, 2.5)
	check(sup != null, "Bdg.superellipse")

func _test_part_constructors() -> void:
	var bx := Bdg.box(10.0, 10.0, 10.0)
	check(bx != null, "Bdg.box")
	var cyl := Bdg.cylinder(5.0, 15.0)
	check(cyl != null, "Bdg.cylinder")
	var sph := Bdg.sphere(8.0)
	check(sph != null, "Bdg.sphere")
	var cn := Bdg.cone(8.0, 4.0, 12.0)
	check(cn != null, "Bdg.cone")
	var tor := Bdg.torus(15.0, 4.0)
	check(tor != null, "Bdg.torus")
	var wd := Bdg.wedge(10.0, 10.0, 10.0, 0.0, 0.0, 5.0, 5.0)
	check(wd != null, "Bdg.wedge")
	var poly_pts := [Vector3(0, 0, 0), Vector3(10, 0, 0), Vector3(5, 10, 0), Vector3(5, 5, 10)]
	var cp := Bdg.convex_polyhedron(poly_pts)
	check(cp != null, "Bdg.convex_polyhedron")

func _test_holes_and_fasteners() -> void:
	var h := Bdg.hole(3.0, 10.0)
	check(h != null, "Bdg.hole")
	var cb := Bdg.counter_bore_hole(3.0, 15.0, 6.0, 4.0)
	check(cb != null, "Bdg.counter_bore_hole")
	var cs := Bdg.counter_sink_hole(3.0, 15.0, 6.0, 90.0)
	check(cs != null, "Bdg.counter_sink_hole")
	var bolt := Bdg.hex_bolt(3.0, 20.0)
	check(bolt != null, "Bdg.hex_bolt")
	var nut := Bdg.hex_nut(3.0)
	check(nut != null, "Bdg.hex_nut")
	var shcs := Bdg.socket_head_screw(3.0, 20.0)
	check(shcs != null, "Bdg.socket_head_screw")

func _test_operations() -> void:
	var b1 := Bdg.box(10.0, 10.0, 10.0)
	var b2 := Bdg.box(10.0, 10.0, 10.0).translate(Vector3(5, 0, 0))
	var fused := Bdg.fuse(b1, b2)
	check(fused != null, "Bdg.fuse")
	var mir: Variant = Bdg.mirror(b1, BdgPlane.XZ)
	check(mir != null, "Bdg.mirror")
	var sc: Variant = Bdg.scale(b1, 2.0)
	check(sc != null, "Bdg.scale")
	var spl: Variant = Bdg.split(b1, BdgPlane.XY, Bdg.Keep.TOP)
	check(spl != null, "Bdg.split")
	var bbox := Bdg.bounding_box(b1)
	check(bbox != null, "Bdg.bounding_box")
	var packed := Bdg.pack([b1, b2], 100.0, 100.0, 2.0)
	check(packed.size() == 2, "Bdg.pack returned 2 packed shapes")

func _test_joints_and_drafting() -> void:
	var rj := Bdg.rigid_joint(Bdg.location(Vector3(10, 0, 0)), Bdg.location())
	check(rj != null, "Bdg.rigid_joint")
	var revj := Bdg.revolute_joint(Bdg.location(), Bdg.location(), BdgAxis.Z)
	check(revj != null, "Bdg.revolute_joint")
	var linj := Bdg.linear_joint(Bdg.location(), Bdg.location(), BdgAxis.X)
	check(linj != null, "Bdg.linear_joint")
	var asm := Bdg.assembly(null, "TestAssembly")
	check(asm != null, "Bdg.assembly")
	var dim := Bdg.dimension_line(Vector3.ZERO, Vector3(50, 0, 0))
	check(dim != null, "Bdg.dimension_line")
	var td := Bdg.technical_drawing()
	check(td != null, "Bdg.technical_drawing")

func _test_io() -> void:
	var test_box := Bdg.box(10.0, 10.0, 10.0)
	var step_ok := Bdg.export_step(test_box, "user://test_parity.step")
	check(step_ok, "Bdg.export_step")
	var brep_ok := Bdg.export_brep(test_box, "user://test_parity.brep")
	check(brep_ok, "Bdg.export_brep")
	var stl_ok := Bdg.export_stl(test_box, "user://test_parity.stl")
	check(stl_ok, "Bdg.export_stl")
	var obj_ok := Bdg.export_obj(test_box, "user://test_parity.obj")
	check(obj_ok, "Bdg.export_obj")
	var ply_ok := Bdg.export_ply(test_box, "user://test_parity.ply")
	check(ply_ok, "Bdg.export_ply")
	var gltf_ok := Bdg.export_gltf(test_box, "user://test_parity.gltf")
	check(gltf_ok, "Bdg.export_gltf")

	var imp_step := Bdg.import_step("user://test_parity.step")
	check(imp_step != null, "Bdg.import_step")
	var imp_brep := Bdg.import_brep("user://test_parity.brep")
	check(imp_brep != null, "Bdg.import_brep")
	var imp_stl := Bdg.import_stl("user://test_parity.stl")
	check(imp_stl != null, "Bdg.import_stl")
